GET http://localhost:3001/api/items
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzYxZDJhZGJmNTdhOWZlNmIxMzBmNSIsInVzZXJuYW1lIjoibGluY2UiLCJpYXQiOjE2NzQwMTE2NDYsImV4cCI6MTY3NDAxMTcwNn0.iRoJ3nI3fSGmyrT9-IGVmrfdXVdcounlp2eq6WNczGw