GET http://localhost:3001/api/items
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzYxZDJhZGJmNTdhOWZlNmIxMzBmNSIsInVzZXJuYW1lIjoibGluY2UiLCJpYXQiOjE2NzQ2MTk1MzIsImV4cCI6MTY3NDg3ODczMn0.MjwXY8vKKmMyYzdpVg9mnnOREuOrZ9i9eHR0HKquBAc